### ISSUE TITLE
Weird Â character in front of EVERYTHING.

### ISSUE THREAD

**Issue by ColeSkory** [xFyreWolfx/BetterShops#1]
There is this weird Â character in front of everything inside the server and log.
https://gyazo.com/d1a9bf43c815f5f35530d4ec676bf6f8
https://gyazo.com/5275155ac249149e37bd45eacab820f4

**Comment by xFyreWolfx** [comment]
Hi ColeSkory,

Did you compile the plugin yourself? This seems to be a common issue when compiling on Windows. As far as the code goes, it doesn't seem to include any of those Â characters (see https://github.com/xFyreWolfx/BetterShops/blob/master/src/max/hubbard/bettershops/Core.java). Any information you can give will be helpful in fixing the issue. In the meantime, feel free to download the pre-compiled version from the Releases page.

Best Regards,
:feet: xFyreWolfx

**Comment by ColeSkory** [comment]
Hi xFyreWolfx,

Thanks for replying.
Unfortunately, I did not compile it myself, I had a contact who helped me out with it. :/
I will head on over there then, thanks a ton!

Cole Skory

**Comment by xFyreWolfx** [comment]
No problem! Let me know if you find any other issues :)
