### ISSUE TITLE
"Can't afford Iron Ingots" when a player clearly can. GLITCH

### ISSUE THREAD

**Issue by ColeSkory** [xFyreWolfx/BetterShops#2]
Hello, again...
I'll use the example of what was going on a little bit ago.

A stack of 32 iron ingots on my server cost $9600 (I know it's extremely expensive.. I fixed that :P) A player couldn't afford a full stack so they tried to only purchase two. Because their account balance ($4000) was less than the total amount of the 32 stacks ($9000) it told them they couldn't afford 2 iron ingots. I realized this was the problem when I lowered the price of the ingots and it worked; Which is really only a temporary solution until a player with only $1000 dollars tried to purchase a single ingot. Ha!

Pretty weird....

**Comment by xFyreWolfx** [comment]
Hi ColeSkory,

It looks like there might be an economy issue here. Could you please supply the following information for me?

1. Your Server Version (/version)
2. Your BetterShops version
3. Your Economy plugin (Essentials, iConomy, etc.)
4. Steps to reproduce the problem
  a. Does it happen every time?
  b. What happens if you change one of your steps?
  c. Is there anything else I should know in order to find the bug on my own server?

Using the list above will help me in finding the issue for you. If your server has any errors ("**stack traces**), be sure to paste them in here as well.

Thanks!
:feet: ~xFyreWolfx

**Comment by ColeSkory** [comment]
Hi xFyreWolfx,

First off, I want to apologize for not getting back to you on this issue. I recently moved back to Arizona so that has been distracting me from most things.

I am using Minecraft Spigot version 1.10-R0.1-SNAPSHOT
BetterShops version 2.1.31
And I am just using Essentials.

I think the only thing to do would be to set the price of an item higher than your max balance and try to purchase a single ingot.

I have also noticed that I can not purchase bulk items of higher cost. For example; I can not purchase two stacks of iron ingots when they are sold in quantities of 32 as it tells me that "I cannot afford that item"
 https://gyazo.com/757c7aa47a94441c928339dd1086e021
https://gyazo.com/4fff2d1891d61b0477d720eca7ee7982
https://gyazo.com/266715ef96d1349274e203491e336960
But I can easily purchase 10+ stacks of something that is largely cheaper: Rotten Flesh.

https://gyazo.com/29090f2dab633c57e2b899d76fbfb694
https://gyazo.com/7459f816217a36ba827a793554320a91
https://gyazo.com/f513d5056e494ce0ee2be8193e956e87

To the best of my knowledge, I don't have any trace errors.


UPDATE:
Upon purchasing that insane amount of Rotten Flesh, I realized that once my inventory gets full the items that don't fit into my inventory just disappear without notifying me that my inventory is full
Example: If you only have three slots available in your inventory and you buy seven stacks of something you will only get three stacks even though you paid for four.

Thanks,
Cole.

**Comment by ColeSkory** [comment]
Just bumping this thread. Not sure if you aren't seeing this because it's so old.... 

Thanks,
Cole

**Comment by ColeSkory** [comment]
Bumping again

**Comment by xFyreWolfx** [comment]
Hi Cole,

Unfortunately it seems like this is a code problem as well - from what I hear, the original version has a few problems as it is. My build really only adds 1.10.x support, so any bugs that were present would also be present in my case. While I'm happy to check things out, it would probably be most beneficial to talk to the original developer at https://github.com/moomaxie/BetterShops/issues, and/or check out some of the other custom builds (https://github.com/Robotia/BetterShops, https://github.com/Majncraft/BetterShops).

I hope that helps!
