### ISSUE TITLE
Is this a plugin?

### ISSUE THREAD

**Issue by QueenKisaki** [xFyreWolfx/BetterShops#3]
I've uploaded Better Shops to my server and try running using it but nothing happens and no errors in console either. I'm using Spigot1.10.2 and used your master zip version. Please tell me what I'm doing wrong lol
 Yes, I've unzipped the folder too. Am I supposed to be using this in conjuction with the original BetterShops? I didn't do that but not sure why yours is not working.

**Comment by xFyreWolfx** [comment]
You'll need to grab the compiled .JAR file from the Releases page: https://github.com/xFyreWolfx/BetterShops/releases - the .ZIP folder that GitHub creates can't be used as a plugin, as Bukkit/Spigot can only read .JAR

I hope that helps!
:feet: FyreWolf

**Comment by QueenKisaki** [comment]
Yes I have that jar file installed along with the entire download from your page and when it loads up I only get a folder but nothing happens in game.

**Comment by QueenKisaki** [comment]
I just restarted again and found this:

29.09 16:13:59 [Server] INFO BetterShops - Enabling BetterShops 2.1.2
29.09 16:13:59 [Server] INFO BetterShops - Could not find support for this CraftBukkit version. Currently Supports CB version 1.7.9 RO.3 - Spigot 1.8.R1, You are using v1_10_R1. Plugin Disabling!
