### ISSUE TITLE
sorry still nothing

### ISSUE THREAD

**Issue by QueenKisaki** [xFyreWolfx/BetterShops#4]
Think you wont see it as you closed the last ticket but I'm getting this in console:

29.09 16:13:59 [Server] INFO BetterShops - Enabling BetterShops 2.1.2
29.09 16:13:59 [Server] INFO BetterShops - Could not find support for this CraftBukkit version. Currently Supports CB version 1.7.9 RO.3 - Spigot 1.8.R1, You are using v1_10_R1. Plugin Disabling!

Where do I install your unzipped folder to because I've just uploaded it to my plugins directory. And was running the BetterShops.jar too when I got that error above

**Comment by ColeSkory** [comment]
Maybe you are running the wrong version of Spigot..... What happens if you do /version?

**Comment by xFyreWolfx** [comment]
It looks like you're running v2.1.2, which is **not** my build, it's the original. [Click here](https://github.com/xFyreWolfx/BetterShops/releases/download/v2.1.31/BetterShops.jar) to directly download my version, 2.1.31 :)
