### ISSUE TITLE
NPC

### ISSUE THREAD

**Issue by QueenKisaki** [xFyreWolfx/BetterShops#5]
Hey Fyre thank you. I got it working now, the only thing I can't get working tho is the npc's part. The eggs are all white and nothing happens when I try to click one. Is there maybe a conflict between it and Citizens?  I don't get errors in console either. Holograms work fine, everything else does too, just the npcs. I have them still enabled in the config as well.

edit: Getting this in console now 30.09 12:46:43 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin BetterShops v2.1.31 generated an exception while executing task 3102973

**Comment by xFyreWolfx** [comment]
Hi QueenKisaki,

It looks like that's an issue with the code itself. My build isn't too spectacular as it simply updates the plugin to 1.10.x - I recommend checking out https://github.com/moomaxie/BetterShops/issues and perhaps posting the issue there :)
