### ISSUE TITLE
Update to 1.11.2

### ISSUE THREAD

**Issue by Rkaynjehll** [xFyreWolfx/BetterShops#6]
Pretty pretty please? :)

**Comment by xFyreWolfx** [comment]
Hi Rkaynjehll,

Unfortunately, I haven't been maintaining this fork of BetterShops for a while now, so an update to 1.12 isn't in the works. I recommend taking a look at https://github.com/Majncraft/BetterShops for the most up-to-date fork available. 

I hope that helps! :)
